name: 'Dorametrix'
description: 'Conveniently create a deployment event in Dorametrix'
branding:
  icon: 'package'
  color: 'green'
inputs:
  endpoint:
    description: 'Dorametrix API endpoint, in the format: "https://mydomain.com/stagename"'
    required: true
    default: ''
  api-key:
    description: 'Dorametrix API token'
    required: true
    default: ''
  product:
    description: '(Optional) Product name, will default to repository name'
    required: false
    default: ${{ github.event.repository.name }}
runs:
  using: "composite"
  steps:
    - run: ${{ github.action_path }}/deployment.sh ${{ inputs.endpoint }} ${{ inputs.api-key }} ${{ inputs.product }}
      shell: bash