on: [push]

jobs:
  dorametrix:
    runs-on: ubuntu-latest
    name: Dorametrix
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Login to Github Packages
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push image to GitHub Container Registry
        uses: docker/build-push-action@v2
        with:
          tags: |
            ghcr.io/mikaelvesavuori/dorametrix-pipe:1.0.0
          push: ${{ github.ref == 'refs/heads/main' }}
